#Container based testing
sudo: false
language: cpp
compiler: gcc
branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - kubuntu-backports
    packages:
      - g++-4.8
      - gcc-4.8
      - libopencv-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libevent-dev 
      - automake 
      - libtool
      - flex
      - bison 
      - pkg-config 
      - libssl-dev 
      - libgoogle-perftools-dev
      
cache:
  directories:
    - $HOME/thrift
      
install:
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - if [ ! -d "$HOME/thrift/lib/pkgconfig" ]; then wget http://www.us.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz && tar axvf thrift-0.9.2.tar.gz && pushd thrift-0.9.2 && ./configure --prefix=$HOME/thrift --without-qt4 --without-qt5 --without-c_glib --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-ruby --without-haskell --without-go --without-haxe --without-d --disable-tests --disable-tutorial --disable-coverage && make -j8 && make install && popd; fi
script:
  - $CXX --version
  - $CC --version
  - export PATH=$PATH:$HOME/thrift/bin
  - export PKG_CONFIG_PATH=$HOME/thrift/lib/pkgconfig
  - cd code/
  - ./configure -DBUILD_OPTIONALS=YES -Dtest=ON
  - make
  - make test ARGS="-V"