language: cpp
compiler: gcc
branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8 gcc-4.8 libopencv-dev
  - sudo apt-get install -qq boost1.55 libevent-dev automake libtool flex bison pkg-config libssl-dev libgoogle-perftools-dev
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - wget http://www.us.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz
  - tar axvf thrift-0.9.2.tar.gz
  - pushd thrift-0.9.2 && ./configure --without-qt4 --without-qt5 --without-c_glib --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-ruby --without-haskell --without-go --without-haxe --without-d --disable-tests --disable-tutorial --disable-coverage && make -j8 && sudo make install && popd
  #- pushd thrift-0.9.2 && cd compiler/cpp && cmake . && make -j8 && sudo make install && popd
script:
  - $CXX --version
  - $CC --version
  - cd code/
  - ./configure -DDISABLE_NONFREE=YES -Dtest=ON
  - make
  - make test ARGS="-V"